### ISSUE TITLE
Invalid entries in feed throws uncaught IllegalArgumentException

### ISSUE THREAD

**Issue by qjqqyy** [CS2103-AY1819S2-W10-1/main#136]
When trying to view a feed that has an entry considered invalid by us, `IllegalArgumentException` was thrown to stdout instead of providing feedback to the user.

An example is https://en.wikipedia.org/wiki/Symphony_No._33_(Mozart) in https://www.bing.com/search?q=33&format=rss

## Related to
* #135

**Comment by thomastanck** [comment]
Resolved by #157.
