### ISSUE TITLE
Entry management: Make Link validation regex more permissive

### ISSUE THREAD

**Issue by rlrh** [CS2103-AY1819S2-W10-1/main#42]
This is the current validation regex for Link:
```java
private static final String PATH = "[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]";
public static final String VALIDATION_REGEX = "^(https?|ftp|file)://" + PATH;
```
We can modify it to be more permissive as `file:` does not need double slashes.

With this change, entries in `TypicalEntries` can be simplified from 
`"file://" + MainApp.class.getResource("somefile").toExternalForm().substring(5)` 
to just
`MainApp.class.getResource("somefile").toExternalForm()`.

**Comment by epicfailname** [comment]
```public static final String VALIDATION_REGEX = "^(https?|ftp|file)://" + PATH;```
to
```public static final String VALIDATION_REGEX = "^(https?://|file:/(//)?)" + PATH;```

**Comment by thomastanck** [comment]
lgtm
