### ISSUE TITLE
As a user, I can add a link with title, description and other helpful metadata automatically extracted

### ISSUE THREAD

**Issue by rlrh** [CS2103-AY1819S2-W10-1/main#46]
so I can conveniently save the link for future reference.

### Part of epics:
- #24 Entry management 
- #25 RSS feed support
- #28 Offline support

### Sub-tasks in:
- #43 Entry management: Make link field the only required field in AddCommand 
- #47 Model: When adding entry, fill in missing fields by extracting metadata from web page

### Related to:
- #26 As a frequent user, I want to add links from feeds

**Comment by thomastanck** [comment]
Resolved by #76.
