### ISSUE TITLE
RFC: Use case for adding of entries

### ISSUE THREAD

**Issue by epicfailname** [CS2103-AY1819S2-W10-1/main#51]
In all use cases of adding an entry, users will have to fill in the `Link` field. At any time, users should also be allowed to edit the `Title` and `Description` field of an existing entry. 

However, should the `Title` and `Description` field be allowed as a user-input field when adding an entry?

Option 1:
Allow users to optionally* input `Title` and `Description` fields as well. Behind the scenes, the Crux library will only update the fields that are not filled in by the users (doesn't override).

Option 2:
Users can only input the `Link` field. Crux library will fill in both `Title` and `Description` fields, after which users can edit the `Title` and `Description` fields according to their preferences.

**Comment by qjqqyy** [comment]
why not allow both options? Maybe let title and description overrides be optional so both use cases are applicable?

**Comment by rlrh** [comment]
I'm in favour of Option 1, as from a product design point of view, if a user wants to override the title and description, he/she would already have them in mind, so it makes more sense to override them while adding an entry than after.
We also have this recommendation in the project info:
> One-shot commands are faster over multi-step commands . If you provide a multi-step command to help new users, you can also provide a one-shot equivalent for regular/expert users.  Reason: We want the user to be able to accomplish tasks faster using CLI than a GUI; having to enter commands part-by-part will slow down the user.

**Comment by epicfailname** [comment]
> why not allow both options? Maybe let title and description overrides be optional so both use cases are applicable?

My mistake, I meant for option 1 to be optional `Title` and `Description` fields. It only allows user the option of inputting those fields immediately.

**Comment by rlrh** [comment]
> why not allow both options? Maybe let title and description overrides be optional so both use cases are applicable?

I believe this is what option 1 actually means.

**Comment by epicfailname** [comment]
> I'm in favour of Option 1, as from a product design point of view, if a user wants to override the title and description, he/she would already have them in mind, so it makes more sense to override them while adding an entry than after.
> We also have this recommendation in the project info:
> 
> > One-shot commands are faster over multi-step commands . If you provide a multi-step command to help new users, you can also provide a one-shot equivalent for regular/expert users.  Reason: We want the user to be able to accomplish tasks faster using CLI than a GUI; having to enter commands part-by-part will slow down the user.

My concern is then how should `Model` detect if an Entry has user-inputted `Title` and `Description` fields, and if Crux is able to garuntee fillling these fields.

**Comment by thomastanck** [comment]
> Option 1:
> Allow users to optionally* input `Title` and `Description` fields as well. Behind the scenes, the Crux library will only update the fields that are not filled in by the users (doesn't override).
> 
> Option 2:
> Users can only input the `Link` field. Crux library will fill in both `Title` and `Description` fields, after which users can edit the `Title` and `Description` fields according to their preferences.

I think option 1 is best, but within it there are 2 more approaches

Approach 1.1:
We interpret this as a "best effort autocompletion". If the user does not specify, we autocomplete the fields by running crux on it, and if crux is not able to, we insert defaults (e.g. title := link, description := ""). The upside is that this is very easy to implement, no extra change needed aside from autocompletion.

The downside is that if the link was something like Wikipedia, and the user reloads the cached copy, we cannot update the description to the new one, since we don't know if the description originated from a user specified one (which we don't want to override) or a crux generated one (which we probably want to update).

Approach 1.2:
We save crux fields separately, and have the UI display the user field if it exists, else the crux field, else the default. This resolves the wikipedia link problem. But it does mean it gets a bit more involved to implement

**Comment by epicfailname** [comment]
> > Option 1:
> > Allow users to optionally* input `Title` and `Description` fields as well. Behind the scenes, the Crux library will only update the fields that are not filled in by the users (doesn't override).
> > Option 2:
> > Users can only input the `Link` field. Crux library will fill in both `Title` and `Description` fields, after which users can edit the `Title` and `Description` fields according to their preferences.
> 
> I think option 1 is best, but within it there are 2 more approaches
> 
> Approach 1.1:
> We interpret this as a "best effort autocompletion". If the user does not specify, we autocomplete the fields by running crux on it, and if crux is not able to, we insert defaults (e.g. title := link, description := ""). The upside is that this is very easy to implement, no extra change needed aside from autocompletion.
> 
> The downside is that if the link was something like Wikipedia, and the user reloads the cached copy, we cannot update the description to the new one, since we don't know if the description originated from a user specified one (which we don't want to override) or a crux generated one (which we probably want to update).
> 
> Approach 1.2:
> We save crux fields separately, and have the UI display the user field if it exists, else the crux field, else the default. This resolves the wikipedia link problem. But it does mean it gets a bit more involved to implement

It seems like most of us are in favor of Option 1.

I like approach 1.1 as suggested by Thomas. Will go with it for now!
