### ISSUE TITLE
Entry management: Make add command format more user-friendly by removing l/

### ISSUE THREAD

**Issue by rlrh** [CS2103-AY1819S2-W10-1/main#63]
Currently the add command format is `add l/URL [ti/TITLE] [d/DESCRIPTION] [t/TAG]`.
To make it more user-friendly, we can simplify it to `add URL [ti/TITLE] [d/DESCRIPTION] [t/TAG]`.
This would make adding a link take as little as 3 key presses (using the alias): `a URL` !

**Comment by thomastanck** [comment]
Closing this because we decided that the 2 character convenience is not worth making the command syntax inconsistent. In the long run, users will find it easier to learn new commands if every command used a single unified command syntax.
