### ISSUE TITLE
As a regular user, I can subscribe to multiple feeds and list all of them

### ISSUE THREAD

**Issue by epicfailname** [CS2103-AY1819S2-W10-1/main#69]
so that I can easily navigate between my favorite feeds.

### Part of epics:
- #25 RSS feed support

### Sub-tasks:
- #79 context-swinging
- #71 multiple EntryBooks in Model (EntryBook containing feeds)

### Related to:

**Comment by qjqqyy** [comment]
basic functionality already added in #114 
to be enhanced
