### ISSUE TITLE
Documentation: Update for v1.2

### ISSUE THREAD

**Issue by qjqqyy** [CS2103-AY1819S2-W10-1/main#82]
This issue tracks what we need to do for our documentation for v1.2.
It might be useful to refer to [feedback received from v1.1](https://github.com/nus-cs2103-AY1819S2/addressbook-level4/pull/35#pullrequestreview-212603735).

#### [About Us](https://github.com/CS2103-AY1819S2-W10-1/main/blob/master/docs/AboutUs.adoc)
- [x] update each member's responsibilities

#### [User Guide](https://github.com/CS2103-AY1819S2-W10-1/main/blob/master/docs/UserGuide.adoc)
- [x] label which features are done and which are coming in v2.0
- [x] #75 removes the undo/redo feature, the user guide should be updated
- [x] replace `Ui.png` with an actual screenshot

#### [Developer Guide](https://github.com/CS2103-AY1819S2-W10-1/main/blob/master/docs/DeveloperGuide.adoc)
- [ ] group and order user stories by priority [DEFERRED TO mid-v1.3]
- [ ] quantify "heavy" and "above average typing speed" [DEFERRED TO mid-v1.3]
- Each member should describe the implementation of at least one enhancement he has added (around 1 page for v1.2)
    - [x] @epicfailname - #87 
    - [x] @qjqqyy - #84 
    - [x] @rlrh - #85
    - [x] @thomastanck

**Comment by epicfailname** [comment]
We should use branching workflow for this so we can all work on it simultaneously. I'll create a branch, let's work from there!

**Comment by qjqqyy** [comment]
Should we delete the [undo/redo parts in developer guide](https://github.com/CS2103-AY1819S2-W10-1/main/blob/master/docs/DeveloperGuide.adoc#31-undoredo-feature) too? Since they were removed.

**Comment by thomastanck** [comment]
Docs have been updated for v1.2
#83 #84 #85 #87 #88.
