### ISSUE TITLE
Offline support: Resolve relative links to absolute links in downloaded web pages

### ISSUE THREAD

**Issue by rlrh** [CS2103-AY1819S2-W10-1/main#99]
Part of #28 

Currently, links in downloaded web pages may be relative, which causes some web pages to display sub-optimally. By resolving any relative links to absolute links, we can display web pages optimally when there is an Internet connection. It also allows users to click on hyperlinks to browse around the web, which we may take advantage of in future with an add command that takes no arguments and adds the current page.

**Comment by thomastanck** [comment]
URLs in CSS attributes are not being converted yet
